package com.zimu.ao.enums;

public enum Status {

	SHOP, BUY, SELL, 
	SHOP_CONSUMABLE, SHOP_TOOLS,
	BAG_CONSUMABLE, BAG_TOOLS, BAG_QUESTITEMS,
	CHAR_STATUS, CHAR_YUEMING, CHAR_LINGXING, CHAR_YETAO, CHAR_LURENJIA,
	BATTLE, NONE,
	NPC
	
}
